### ISSUE TITLE
Does not it support contract inheritance and 'using' grammar?

### ISSUE THREAD

**Issue by seongeunC** [ConsenSys/python-solidity-parser#1]
I want to test my contract file, but it does not work if contract has a 'using' syntax or if contract inherit a contract.

**Comment by noitatum** [comment]
Are you using `objectify`? Because I have the same issue but only when I try to `objectify` the result of `parse_file`. As a workaround I've been using the result of `parse_file` as is.
What I've found is that this parser mistakenly labels "usingForDeclaration" under "name" instead of "type" which is inconsistent with other declarations in this parser and Solidity ast-compact-json output. The exact same thing applies to "InheritanceSpecifier" in base contracts.
Considering I'm getting `KeyError: 'type'` errors in both cases I think this is the source of the issue.

**Comment by tintinweb** [comment]
pushed to pypi (https://pypi.org/project/solidity-parser/). thx @seongeunC & @noitatum for providing the fixes!
